# Generated by Django 5.0 on 2023-12-09 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_rename_task_todo_title_remove_todo_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.time, null=True),
        ),
    ]
